/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "outline-variant": "#e4bdbc",
        "tertiary-fixed-dim": "#bfc7d4",
        "on-surface": "#171c21",
        "secondary-fixed": "#dde4e6",
        "inverse-on-surface": "#ecf1f8",
        "outline": "#906f6f",
        "on-surface-variant": "#5b403f",
        "on-tertiary": "#ffffff",
        "primary-container": "#dd2d42",
        "on-primary-fixed": "#410008",
        "on-primary-fixed-variant": "#920020",
        "primary-fixed-dim": "#ffb3b2",
        "on-error-container": "#93000a",
        "tertiary": "#545d68",
        "on-background": "#171c21",
        "on-secondary-fixed": "#161d1f",
        "secondary-fixed-dim": "#c1c8ca",
        "surface-dim": "#d5dae1",
        "background": "#f6f9ff",
        "surface-tint": "#bc0d2e",
        "on-secondary-fixed-variant": "#41484a",
        "on-error": "#ffffff",
        "secondary-container": "#dae1e3",
        "on-secondary-container": "#5d6466",
        "surface-bright": "#f6f9ff",
        "secondary": "#586062",
        "on-tertiary-fixed": "#141c25",
        "surface-container-low": "#eff4fb",
        "on-tertiary-fixed-variant": "#3f4752",
        "inverse-primary": "#ffb3b2",
        "primary": "#b9082c",
        "surface-container": "#e9eef5",
        "inverse-surface": "#2b3136",
        "error-container": "#ffdad6",
        "primary-fixed": "#ffdad9",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e4e9f0",
        "surface": "#f6f9ff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#6d7581",
        "surface-variant": "#dee3ea",
        "surface-container-highest": "#dee3ea",
        "tertiary-fixed": "#dbe3f0",
        "on-primary-container": "#fffbff",
        "on-tertiary-container": "#fdfcff",
        "error": "#ba1a1a"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
    },
  },
  plugins: [],
}